; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-stickc-plus2]
platform = espressif32@6.7.0
board = m5stick-c
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
board_build.partitions = partition.csv
build_flags = 
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-DCORE_DEBUG_LEVEL=1
	-D CONFIG_BT_ENABLED=1
    -D CONFIG_BT_NIMBLE_ENABLED=1
    -D CONFIG_BTDM_CTRL_MODE_BTDM=1
    -D CONFIG_BTDM_CTRL_BR_EDR_SCO_DATA_PATH_EFF=0
lib_deps = 
	M5Unified=https://github.com/m5stack/M5Unified
	M5StickC-Plus2 = https://github.com/m5stack/M5StickCPlus2.git
	h2zero/NimBLE-Arduino
